name: Build Electron App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        architecture: [x86_64, arm64]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run make

      - name: Compress output files
        run: tar -czvf electron-app.tar.gz -C out

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: electron-app
          path: electron-app.tar.gz
